### ISSUE TITLE
US: User can CRUD events

### ISSUE THREAD

**Issue by AngelaGuardia** [Turing-Eras/api#27]
As a user, I can create, read, update, or delete an event.

**Comment by dhalverson** [comment]
Checking out this to see if I can get a better understanding of GraphQL and Rails. I'm happy to pair with anyone if they would like to work on this as well, and I plan to put up a PR if I can get something working.

I might break this out into individual CRUD tickets.

**Comment by dhalverson** [comment]
Closed this ticket in favor of individual CRUD issues for Events
