### ISSUE TITLE
BE Team - Pending Decisions

### ISSUE THREAD

**Issue by AngelaGuardia** [Turing-Eras/api#39]
- [x] How/when to ignore rubocop validations
- [x] GraphQL query naming convention
- [x] GraphQL mutation naming convetion
- [x] GraphQL Date type implementation

**Comment by AngelaGuardia** [comment]
@leahriffell @dhalverson @LHJE 

- We will ignore all rubocop offenses related to query methods that start with get
- We will name our queries with get*Resource*
- We will name our mutations verb*Resource*

@Teapane What is your advice on how to best work with dates with graphQL and between FE and BE. Our DB is currently storing DateTime for our dates.

**Comment by leahriffell** [comment]
From our check-in: Tyler recommends going w/ String (Date) vs. Int for date storage. Integer/unix time is nice when you're dealing with times but dates are the most granular that we will get. 

If we keep as DateTime, parse out time before sending to FE. Based on this, do we want to change our datatype to Date or String (currently DateTime)? @AngelaGuardia @LHJE @dhalverson
